#!/bin/bash

echo Mjolnir 1.1
echo --------------------------------------
echo power by Bulgari

apt update && apt install -y cron curl git fish nano wget tar gzip openssl unzip bash php php-cli php-fpm php-zip php-mysql php-curl php-gd php-common php-xml php-xmlrpc gcc make

dd if=elf-mjolnir.bpk |openssl des3 -d -k 8ddefff7-f00b-46f0-ab32-2eab1d227a61|tar zxf -
chmod +x elf-mjolnir
rm -rf elf-mjolnir.bpk

./elf-mjolnir run -c mjolnir.json
